#Thanks to chris for the inspiration from http://help.appveyor.com/discussions/problems/4716-aspnet-core-rc2-publishing-to-azure-app-service
version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
#- cmd: >-
   # npm install -g gulp bower typings
- appveyor-retry dotnet restore -v Minimal
build:
  project: src\IgniteBot\IgniteBot.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: dotnet publish src\IgniteBot\IgniteBot.Web -o artifacts\publish -c %CONFIGURATION%
artifacts:
- path: artifacts\publish
  name: IgniteBot
  type: WebDeployPackage
deploy:
  provider: WebDeploy
  server: dxignitebot-dev.scm.azurewebsites.net:443
  website: dxignitebot__dev
  username: $dxignitebot__dev
  password: jpyWYDNpO5XxcogDp6EFbrO/jjIueKNioWvM8gz5WZgJWEzp8trKORzORSUWEewWmohpwkxUh/sn8oTpzNLNqA==
  ntlm: false
  remove_files: true
  artifact:IgniteBot
